### ISSUE TITLE
[FEAT] Add custom walls and mud to MazeCOnfig

### ISSUE THREAD

**Issue by mintiti** [mintiti/pyrat-engine#14]
## Feature Description
Add the possibility to pass custom walls and mud to a maze config

## Purpose
Customize labyrinth initialization

### Describe the feature and the current behaviour.
RIght now we cant

## Implementation Steps and/or Challenges

- [ ] Create relevant enums 
- [ ] Add walls and mud into config
- [ ] Make sure the initializer handles the new fields correctly 

### Will this change the current API? If so, how?
Yes, MazeConfig will have new
