### ISSUE TITLE
[FEAT] Create wall initializer

### ISSUE THREAD

**Issue by mintiti** [mintiti/pyrat-engine#17]
## Feature Description
Create the generator for the walls.

## Purpose
Walls need to be initialized randomly with some constraints (whether the maze is connected or not, whether it is symmetrical)

### Describe the feature and the current behaviour.
The Initializer doesn't exist right now 

## Implementation Steps and/or Challenges

- [ ] Wall initializer exists
- [ ] wall initializer can create symmetrical and non symmetrical mazes
- [ ] Wall initializer can create connected and not connected mazes
- [ ] Wall initializer can create mazes in any combination of the above
- [ ] Implement Wall generator in the initilizer
