### ISSUE TITLE
[FEAT] Create mud generator

### ISSUE THREAD

**Issue by mintiti** [mintiti/pyrat-engine#18]
## Feature Description
Create the mud generator.

## Purpose
Generate mud from a given config

### Who will benefit from this feature?
Maze initialization

## Implementation Steps and/or Challenges

- [ ] Create the mud generator 
- [ ] Mud generator can create symmetrical and asymmetrical muds
- [ ] Mud generator can create mud from custom mud list
- [ ] Mud generator is in the initializer

### Will this change the current API? If so, how?
No
