### ISSUE TITLE
[FEAT] Make benchmark utilities

### ISSUE THREAD

**Issue by mintiti** [mintiti/pyrat-engine#22]
## Feature Description
We need to be able measure the engine's performance.
To do so, we want to build some benchmarking tools

## Purpose
Measure, profile engine functionalities and help making the code faster in the long run

## Implementation Steps and/or Challenges

- [x] Define key metrics (e.g. positions per seconds, time to set positions ? )
- [x] Define problem variables (e.g labyrinth size, nb_cheese, ....)
- [x] Implement benchmarkers that output benchark suites on given metrics and changing problem variables on an engine.

### Will this change the current API? If so, how?
No
