### ISSUE TITLE
[FEAT] Jax engine implementation

### ISSUE THREAD

**Issue by mintiti** [mintiti/pyrat-engine#30]
## Feature Description
Implement the Jax version of the engine

## Purpose
Native running on GPU/TPUs to run full algorithms on accelerators

## Implementation Steps and/or Challenges

- [ ] Implement the engine
- [ ] Unit test the engine
- [ ] Benchmark the engine
