### ISSUE TITLE
[FEAT] Create github actions matching pre-commit hooks

### ISSUE THREAD

**Issue by mintiti** [mintiti/pyrat-engine#5]
## Feature Description
To ensure consistent codebase, enable github actions checking for code style

### Who will benefit from this feature?
Library codebase style at large

## Implementation Steps and/or Challenges

- [x] Create the github actions file
- [x] Make sure the whole codebase passes the actions
- [x] Disable merging without passing the actions 

### Will this change the current API? If so, how?
No

### How do we know when implementation of this feature is complete?

**Checklist**
- [x] Github actions are up to date
- [x] Latest main branch commit passes the actions

**Comment by mintiti** [comment]
#2 closes this
