### ISSUE TITLE
[FEAT] Define Displayer abstraction 

### ISSUE THREAD

**Issue by mintiti** [mintiti/pyrat-engine#9]
## Feature Description
Define the interface for something that displays a single game state

## Purpose
We wanna sometimes visualize a single game state. It could be useful for debugging purposes, and generally seeing the game.

### Describe the feature and the current behaviour.
We currently only have PGN to describe the state of a game

We now want something like this : 
PGN -> process PGN -> make a visual representation of the game

## Implementation Steps and/or Challenges

- [x] Create the interface
- [x] Make sure it is compatible with PyGame
- [ ] Make a simple displayer

### Will this change the current API? If so, how?
NO
